In [11]:
# NumPy Fundamentals - Student Lab

## Lab Instructions

#Complete all exercises below. Write your code in a Python file or Jupyter notebook. Test each task to ensure it produces the expected output.

#**Assessment Criteria:**
#- Code correctness and functionality
#- Proper use of NumPy functions
#- Code efficiency (use vectorized operations)
#- Clean, readable code with appropriate comments

In [10]:
## Exercise 1: Array Creation and Attributes (15 points)

### Task 1.1: Create arrays using different methods (10 points)

#Write code to create the following arrays:

#1. A 1D array containing values from 0 to 9
#2. A 2D array (3x3) containing values from 1 to 9
#3. A 3x4 array filled with zeros#
#4. A 2x5 array filled with ones (data type: float32)
#5. A 4x4 identity matrix#
#6. An array with values from 10 to 50 with step size 5
#7. An array with 8 evenly spaced values between 0 and 1

#Solution
import numpy as np

# 1. 1D array containing values from 0 to 9
# np.arange is efficient for creating sequences
arr_1d = np.arange(10)

# 2. 2D array (3x3) containing values from 1 to 9
# Reshape converts 1D array into required dimensions
arr_2d = np.arange(1, 10).reshape(3, 3)

# 3. 3x4 array filled with zeros
# np.zeros creates an array filled with 0s
zeros_array = np.zeros((3, 4))

# 4. 2x5 array filled with ones (data type: float32)
# dtype ensures correct data type
#=========In this code, I used AI to understand NumPy operations related to data types such as float and also for linespace array=============
ones_array = np.ones((2, 5), dtype=np.float32)

# 5. 4x4 identity matrix
# np.eye creates an identity matrix
identity_matrix = np.eye(4)

# 6. Array with values from 10 to 50 with step size 5
# arange allows step control
step_array = np.arange(10, 51, 5)

# 7. Array with 8 evenly spaced values between 0 and 1
# linspace is best for evenly spaced values
linspace_array = np.linspace(0, 1, 8)
print("1D Array:", arr_1d)
print("\n2D Array:\n", arr_2d)
print("\nZeros Array:\n", zeros_array)
print("\nOnes Array (float32):\n", ones_array)
print("\nIdentity Matrix:\n", identity_matrix)
print("\nStep Size Array:", step_array)
print("\nLinspace Array:", linspace_array)


1D Array: [0 1 2 3 4 5 6 7 8 9]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array (float32):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Step Size Array: [10 15 20 25 30 35 40 45 50]

Linspace Array: [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [13]:

### Task 1.2: Explore array attributes (5 points)
#Create a 3x4 array with values from 1 to 12. Print the following attributes:
#- Shape
#- Number of dimensions
#- Total number of elements
# Data type
#- Item size in bytes
#- Total bytes consumed
#solution

import numpy as np

# Create a 3x4 array with values from 1 to 12
# np.arange generates values efficiently, reshape gives required dimensions
arr = np.arange(1, 13).reshape(3, 4)

# Print array attributes
print("Array:\n", arr)

# Shape of the array (rows, columns)
print("Shape:", arr.shape)

# Number of dimensions (1D, 2D, etc.)
print("Number of dimensions:", arr.ndim)

# Total number of elements in the array
print("Total number of elements:", arr.size)

# Data type of elements in the array
print("Data type:", arr.dtype)

# Size of one element in bytes
print("Item size (bytes):", arr.itemsize)

# Total memory consumed by the array (in bytes)
print("Total bytes consumed:", arr.nbytes)




Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Number of dimensions: 2
Total number of elements: 12
Data type: int64
Item size (bytes): 8
Total bytes consumed: 96


In [3]:
## Exercise 2: Indexing and Slicing (20 points)

### Task 2.1: Basic indexing (5 points)

import numpy as np

# -----------------------------
# 1D Array Indexing
# -----------------------------

# Given 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 1. Access the first element (index 0)
first_element = arr[0]

# 2. Access the last element using negative indexing
last_element = arr[-1]

# 3. Access the 5th element (index 4 because indexing starts from 0)
fifth_element = arr[4]

print("First element:", first_element)
print("Last element:", last_element)
print("5th element:", fifth_element)


# -----------------------------
# 2D Array Indexing
# -----------------------------

# Create a 2D array with shape (3, 4)
arr_2d = np.arange(1, 13).reshape(3, 4)

print("\n2D Array:\n", arr_2d)

# Access element at row 1, column 2
# (Indexing starts from 0)
element_1_2 = arr_2d[1, 2]

# Access element at row 0, column 3
element_0_3 = arr_2d[0, 3]

# Access the last element using negative indexing
last_element_2d = arr_2d[-1, -1]

print("Element at row 1, column 2:", element_1_2)
print("Element at row 0, column 3:", element_0_3)
print("Last element of 2D array:", last_element_2d)


First element: 10
Last element: 100
5th element: 50

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row 1, column 2: 7
Element at row 0, column 3: 4
Last element of 2D array: 12


In [4]:
### Task 2.2: Slicing operations (8 points)
import numpy as np

# -----------------------------
# 1D Array Slicing
# -----------------------------

# Create array from 0 to 19
arr = np.arange(0, 20)

# 1. Extract elements from index 5 to 15 (inclusive)
# Upper bound is exclusive, so we use 16
slice_5_15 = arr[5:16]

# 2. Extract every 3rd element from the array
every_third = arr[::3]

# 3. Reverse the entire array using slicing
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Elements from index 5 to 15:", slice_5_15)
print("Every 3rd element:", every_third)
print("Reversed array:", reversed_arr)


# -----------------------------
# 2D Array Slicing
# -----------------------------

# Create a 4x4 2D array
arr_2d = np.arange(1, 17).reshape(4, 4)

print("\n2D Array:\n", arr_2d)

# Extract the first 2 rows and first 3 columns
#===============I use AI for how to extract 2 rows and 3 columns===========
first_rows_cols = arr_2d[:2, :3]

# Extract the last 2 rows and last 2 columns
last_rows_cols = arr_2d[-2:, -2:]

# Extract every other row with all columns
alternate_rows = arr_2d[::2, :]

print("\nFirst 2 rows and first 3 columns:\n", first_rows_cols)
print("\nLast 2 rows and last 2 columns:\n", last_rows_cols)
print("\nEvery other row (all columns):\n", alternate_rows)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elements from index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every 3rd element: [ 0  3  6  9 12 15 18]
Reversed array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First 2 rows and first 3 columns:
 [[1 2 3]
 [5 6 7]]

Last 2 rows and last 2 columns:
 [[11 12]
 [15 16]]

Every other row (all columns):
 [[ 1  2  3  4]
 [ 9 10 11 12]]


In [5]:
### Task 2.3: Boolean and fancy indexing (7 points)
import numpy as np

# Given array
arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])

print("Original array:", arr)

# 1. Extract all values greater than 20 using boolean indexing
greater_than_20 = arr[arr > 20]

# 2. Extract all even numbers
# Modulo (%) operator checks divisibility by 2
even_numbers = arr[arr % 2 == 0]

# 3. Extract values between 10 and 30 (inclusive)
# Combine multiple conditions using logical AND (&)
between_10_30 = arr[(arr >= 10) & (arr <= 30)]

# 4. Fancy indexing: extract elements at indices 0, 3, 5, and 8
indices = [0, 3, 5, 8]
fancy_elements = arr[indices]

# Print results
print("Values greater than 20:", greater_than_20)
print("Even numbers:", even_numbers)
print("Values between 10 and 30:", between_10_30)
print("Fancy indexing result:", fancy_elements)


Original array: [15 23  8 42 11 37 19  5 33 28]
Values greater than 20: [23 42 37 33 28]
Even numbers: [ 8 42 28]
Values between 10 and 30: [15 23 11 19 28]
Fancy indexing result: [15 42 37 33]


In [6]:
## Exercise 3: Array Operations (15 points)

### Task 3.1: Arithmetic operations (8 points)
import numpy as np

# Given arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 10, 15, 20, 25])

# -----------------------------
# Element-wise operations
# -----------------------------

# 1. Element-wise addition
addition = arr1 + arr2

# 2. Element-wise subtraction
subtraction = arr1 - arr2

# 3. Element-wise multiplication
multiplication = arr1 * arr2

# 4. Element-wise division
division = arr1 / arr2

# 5. Square each element of arr1
squared_arr1 = arr1 ** 2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Squared arr1:", squared_arr1)


# -----------------------------
# Scalar operations on arr1
# -----------------------------

# Add 100 to all elements
add_scalar = arr1 + 100

# Multiply all elements by 3
multiply_scalar = arr1 * 3

# Divide all elements by 10
divide_scalar = arr1 / 10

print("\nAdd 100:", add_scalar)
print("Multiply by 3:", multiply_scalar)
print("Divide by 10:", divide_scalar)


Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Division: [2. 2. 2. 2. 2.]
Squared arr1: [ 100  400  900 1600 2500]

Add 100: [110 120 130 140 150]
Multiply by 3: [ 30  60  90 120 150]
Divide by 10: [1. 2. 3. 4. 5.]


In [7]:
### Task 3.2: Universal functions (7 points)
import numpy as np

# -----------------------------
# Universal functions on numbers
# -----------------------------

# Given array
arr = np.array([1, 4, 9, 16, 25, 36])

# 1. Square root of all elements
sqrt_values = np.sqrt(arr)

# 2. Exponential (e^x) of all elements
exp_values = np.exp(arr)

# 3. Natural logarithm of all elements
log_values = np.log(arr)

print("Square root:", sqrt_values)
print("Exponential:", exp_values)
print("Natural logarithm:", log_values)


# -----------------------------
# Trigonometric universal functions
# -----------------------------

# Array of angles (in radians)
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

# Calculate sine and cosine values
sin_values = np.sin(angles)
cos_values = np.cos(angles)

print("\nSine values:", sin_values)
print("Cosine values:", cos_values)


# -----------------------------
# Rounding universal functions
# -----------------------------

# Given decimal array
decimals = np.array([1.23, 2.56, 3.89, 4.12])

# Round to nearest integer
rounded = np.round(decimals)

# Apply floor operation (round down)
#=========== I use AI for understanding what are floor and ceiled ==============
floored = np.floor(decimals)

# Apply ceiling operation (round up)
ceiled = np.ceil(decimals)

print("\nRounded values:", rounded)
print("Floor values:", floored)
print("Ceiling values:", ceiled)


Square root: [1. 2. 3. 4. 5. 6.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]
Natural logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]

Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Rounded values: [1. 3. 4. 4.]
Floor values: [1. 2. 3. 4.]
Ceiling values: [2. 3. 4. 5.]


In [14]:
## Exercise 4: Array Manipulation (20 points)

### Task 4.1: Reshaping and transposing (10 points)

#Create an array with values from 1 to 12, then:
#1. Reshape it to 3x4
#2. Reshape it to 2x6
#3. Reshape it to 2x2x3 (3D array)
#4. Transpose the 3x4 array
#5. Flatten the 3x4 array back to 1D
import numpy as np

# Create a 1D array with values from 1 to 12
arr = np.arange(1, 13)

print("Original 1D array:", arr)

# 1. Reshape the array to 3x4
arr_3x4 = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", arr_3x4)

# 2. Reshape the array to 2x6
arr_2x6 = arr.reshape(2, 6)
print("\nReshaped to 2x6:\n", arr_2x6)

# 3. Reshape the array to 2x2x3 (3D array)
arr_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 2x2x3 (3D array):\n", arr_3d)

# 4. Transpose the 3x4 array (swap rows and columns)
#======================I use AI for tronspose function================
transposed = arr_3x4.T
print("\nTransposed 3x4 array:\n", transposed)

# 5. Flatten the 3x4 array back to 1D
flattened = arr_3x4.flatten()
print("\nFlattened array:", flattened)


Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped to 2x2x3 (3D array):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 3x4 array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
### Task 4.2: Stacking and splitting (10 points)

#Create three 1D arrays: `[1, 2, 3]`, `[4, 5, 6]`, `[7, 8, 9]`

#1. Stack them vertically to create a 3x3 array
#2. Stack them horizontally to create a 1D array

#Create an array from 1 to 12 and:
#- Split it into 4 equal parts

#Create a 4x4 array with values 1-16 and:
#- Split it horizontally into 2 parts
import numpy as np

# -----------------------------
# Stacking 1D arrays
# -----------------------------

# Create three 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
#============Use AI for stack operations=======
# 1. Stack vertically to create a 3x3 array
vertical_stack = np.vstack((a, b, c))

# 2. Stack horizontally to create a 1D array
horizontal_stack = np.hstack((a, b, c))

print("Vertical stack (3x3):\n", vertical_stack)
print("\nHorizontal stack (1D):", horizontal_stack)


# -----------------------------
# Splitting 1D array
# -----------------------------

# Create an array from 1 to 12
arr = np.arange(1, 13)

# Split into 4 equal parts
split_1d = np.split(arr, 4)

print("\nSplit 1D array into 4 equal parts:")
for part in split_1d:
    print(part)


# -----------------------------
# Splitting 2D array
# -----------------------------

# Create a 4x4 array with values from 1 to 16
arr_2d = np.arange(1, 17).reshape(4, 4)

# Split horizontally into 2 parts (along columns)
horizontal_split = np.hsplit(arr_2d, 2)

print("\nOriginal 4x4 array:\n", arr_2d)
print("\nHorizontal split into 2 parts:")
for part in horizontal_split:
    print(part)


Vertical stack (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontal stack (1D): [1 2 3 4 5 6 7 8 9]

Split 1D array into 4 equal parts:
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Horizontal split into 2 parts:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [17]:
## Exercise 5: Statistical Operations (15 points)

### Task 5.1: Basic statistics (7 points)

#Given `arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])`:

#Calculate and print:
#1. Sum of all elements
#2. Mean (average)
#3. Median
#4. Standard deviation
#5. Variance
#6. Minimum value
#7. Maximum value
#8. Index of minimum value
#9. Index of maximum value

#solution
import numpy as np

# Given array
arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])

print("Array:", arr)

# Sum of all elements
total_sum = np.sum(arr)

#  Mean (average)
mean_value = np.mean(arr)

#  Median
median_value = np.median(arr)

# Standard deviation
std_deviation = np.std(arr)

#  Variance
variance_value = np.var(arr)

#  Minimum value
min_value = np.min(arr)

#  Maximum value
max_value = np.max(arr)

#  Index of minimum value
min_index = np.argmin(arr)

#  Index of maximum value
max_index = np.argmax(arr)

# Print results
print("Sum:", total_sum)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
print("Variance:", variance_value)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)



Array: [12 45 23 67 34 89 56 78 90 31]
Sum: 525
Mean: 52.5
Median: 50.5
Standard Deviation: 26.424420523447623
Variance: 698.25
Minimum value: 12
Maximum value: 90
Index of minimum value: 0
Index of maximum value: 8


In [20]:
### Task 5.2: Axis-based statistics (8 points)

#Create a 3x3 array:

#[[10, 20, 30],[40, 50, 60],70, 80, 90]]
#Calculate:
#1. Sum of all elements
#2. Sum along axis 0 (column-wise sum)
#3. Sum along axis 1 (row-wise sum)
#4. Mean along axis 0
#5. Mean along axis 1
#6. Maximum values along axis 0
#7. Maximum values along axis 1
import numpy as np

# Create the 3x3 array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Array:\n", arr)

#  Sum of all elements
total_sum = np.sum(arr)

#  Sum along axis 0 (column-wise sum)
sum_axis_0 = np.sum(arr, axis=0)

#  Sum along axis 1 (row-wise sum)
sum_axis_1 = np.sum(arr, axis=1)

#  Mean along axis 0 (column-wise mean)
mean_axis_0 = np.mean(arr, axis=0)

#  Mean along axis 1 (row-wise mean)
mean_axis_1 = np.mean(arr, axis=1)

#  Maximum values along axis 0 (column-wise max)
max_axis_0 = np.max(arr, axis=0)

#  Maximum values along axis 1 (row-wise max)
max_axis_1 = np.max(arr, axis=1)

# Print results
print("\nTotal sum:", total_sum)
print("Column-wise sum (axis=0):", sum_axis_0)
print("Row-wise sum (axis=1):", sum_axis_1)
print("Column-wise mean (axis=0):", mean_axis_0)
print("Row-wise mean (axis=1):", mean_axis_1)
print("Column-wise max (axis=0):", max_axis_0)
print("Row-wise max (axis=1):", max_axis_1)


Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Total sum: 450
Column-wise sum (axis=0): [120 150 180]
Row-wise sum (axis=1): [ 60 150 240]
Column-wise mean (axis=0): [40. 50. 60.]
Row-wise mean (axis=1): [20. 50. 80.]
Column-wise max (axis=0): [70 80 90]
Row-wise max (axis=1): [30 60 90]


In [21]:
# ## Exercise 6: Real-World Application - Student Grade Analysis (25 points)

# You are given grade data for 5 students across 4 subjects (Math, Science, English, History):

# ```python
# grades = np.array([
#     [85, 90, 78, 88],
#     [92, 88, 95, 90],
#     [76, 82, 80, 75],
#     [88, 85, 90, 92],
#     [95, 92, 88, 94]
# ])
# ```

# **Tasks:**

# 1. **Calculate the average grade for each student** (5 points)
#    - Output should show Student 1: X.XX, Student 2: Y.YY, etc.

# 2. **Calculate the average grade for each subject** (5 points)
#    - Output: Math: X.XX, Science: Y.YY, etc.

# 3. **Find the highest and lowest grades in each subject** (5 points)
#    - Output for each subject: Highest = X, Lowest = Y

# 4. **Identify students with an average grade above 85** (3 points)
#    - Print student number and their average

# 5. **Calculate the overall class average** (2 points)
#    - Average of all grades across all students

# 6. **Normalize all grades to a scale of 0-10** (5 points)
#    - Use min-max normalization formula: (value - min) / (max - min) * 10
#    - Print the normalized grades array

# **Bonus:** Identify the top-performing student (+2 points)

# **Expected Output Format:**
# ```
# --- Task 1: Student Averages ---
# Student 1: XX.XX
# ...
#
# --- Task 2: Subject Averages ---
# Math: XX.XX
# ...
#
# (Continue for all tasks)
# ```

# Solution
import numpy as np

# Given grades array
grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])

subjects = ["Math", "Science", "English", "History"]

# --------------------------------------------------
# Task 1: Average grade for each student
# --------------------------------------------------
student_averages = np.mean(grades, axis=1)

print("--- Task 1: Student Averages ---")
for i, avg in enumerate(student_averages, start=1):
    print(f"Student {i}: {avg:.2f}")


# --------------------------------------------------
# Task 2: Average grade for each subject
# --------------------------------------------------
subject_averages = np.mean(grades, axis=0)

print("\n--- Task 2: Subject Averages ---")
for subject, avg in zip(subjects, subject_averages):
    print(f"{subject}: {avg:.2f}")


# --------------------------------------------------
# Task 3: Highest and lowest grades in each subject
# --------------------------------------------------
subject_max = np.max(grades, axis=0)
subject_min = np.min(grades, axis=0)

print("\n--- Task 3: Highest and Lowest Grades per Subject ---")
for i, subject in enumerate(subjects):
    print(f"{subject}: Highest = {subject_max[i]}, Lowest = {subject_min[i]}")


# --------------------------------------------------
# Task 4: Students with average above 85
# --------------------------------------------------
print("\n--- Task 4: Students with Average Above 85 ---")
for i, avg in enumerate(student_averages, start=1):
    if avg > 85:
        print(f"Student {i}: {avg:.2f}")


# --------------------------------------------------
# Task 5: Overall class average
# --------------------------------------------------
overall_average = np.mean(grades)

print("\n--- Task 5: Overall Class Average ---")
print(f"Overall Average: {overall_average:.2f}")


# --------------------------------------------------
# Task 6: Normalize grades to scale 0–10
# --------------------------------------------------
min_grade = np.min(grades)
max_grade = np.max(grades)

normalized_grades = (grades - min_grade) / (max_grade - min_grade) * 10

print("\n--- Task 6: Normalized Grades (0–10 scale) ---")
print(np.round(normalized_grades, 2))


# --------------------------------------------------
# Bonus: Top-performing student
# --------------------------------------------------
top_student_index = np.argmax(student_averages)

print("\n--- Bonus: Top-Performing Student ---")
print(f"Student {top_student_index + 1} with average {student_averages[top_student_index]:.2f}")


--- Task 1: Student Averages ---
Student 1: 85.25
Student 2: 91.25
Student 3: 78.25
Student 4: 88.75
Student 5: 92.25

--- Task 2: Subject Averages ---
Math: 87.20
Science: 87.40
English: 86.20
History: 87.80

--- Task 3: Highest and Lowest Grades per Subject ---
Math: Highest = 95, Lowest = 76
Science: Highest = 92, Lowest = 82
English: Highest = 95, Lowest = 78
History: Highest = 94, Lowest = 75

--- Task 4: Students with Average Above 85 ---
Student 1: 85.25
Student 2: 91.25
Student 4: 88.75
Student 5: 92.25

--- Task 5: Overall Class Average ---
Overall Average: 87.15

--- Task 6: Normalized Grades (0–10 scale) ---
[[ 5.   7.5  1.5  6.5]
 [ 8.5  6.5 10.   7.5]
 [ 0.5  3.5  2.5  0. ]
 [ 6.5  5.   7.5  8.5]
 [10.   8.5  6.5  9.5]]

--- Bonus: Top-Performing Student ---
Student 5 with average 92.25


In [23]:
# ## Exercise 7: Challenge - Sales Data Analysis (30 points)

# You are analyzing sales data for a company with 4 products over 6 months:

# ```python
# sales_data = np.array([
#     [120, 135, 150, 145, 160, 175],  # Product A
#     [90, 95, 100, 110, 115, 120],    # Product B
#     [150, 145, 155, 160, 170, 180],  # Product C
#     [80, 85, 82, 88, 92, 95]         # Product D
# ])
# ```

# **Tasks:**

# 1. **Calculate total sales for each product** (5 points)
#    - Sum across all months for each product

# 2. **Calculate total sales for each month** (5 points)
#    - Sum across all products for each month (Jan to Jun)

# 3. **Identify the month with the highest total sales** (4 points)
#    - Print the month name and total sales

# 4. **Calculate the growth rate for each product** (6 points)
#    - Growth rate = ((Last month - First month) / First month) × 100
#    - Print as percentage for each product

# 5. **Find products with average monthly sales greater than 120k** (4 points)
#    - Calculate average for each product
#    - Print products meeting the criteria

# 6. **Calculate quarter-wise sales** (6 points)
#    - Q1: January-March
#    - Q2: April-June
#    - Print sales for each product in each quarter

# **Bonus:** Predict next month (July) sales for each product (+5 points)
# - Use a simple method: average of last 2 months + average monthly growth

# **Your Code:**
# ```python
# import numpy as np
#
# sales_data = np.array([
#     [120, 135, 150, 145, 160, 175],
#     [90, 95, 100, 110, 115, 120],
#     [150, 145, 155, 160, 170, 180],
#     [80, 85, 82, 88, 92, 95]
# ])
# ```
#Solution

# In this code i used AI for
import numpy as np

# Sales data for 4 products over 6 months (Jan to Jun)
# Rows -> Products (A, B, C, D)
# Columns -> Months (Jan, Feb, Mar, Apr, May, Jun)
sales_data = np.array([
    [120, 135, 150, 145, 160, 175],  # Product A
    [90, 95, 100, 110, 115, 120],    # Product B
    [150, 145, 155, 160, 170, 180],  # Product C
    [80, 85, 82, 88, 92, 95]         # Product D
])

products = ["Product A", "Product B", "Product C", "Product D"]
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]

# --------------------------------------------------
# Task 1: Total sales for each product
# --------------------------------------------------
product_total_sales = np.sum(sales_data, axis=1)

print("--- Task 1: Total Sales per Product ---")
for product, total in zip(products, product_total_sales):
    print(f"{product}: {total}k")


# --------------------------------------------------
# Task 2: Total sales for each month
# --------------------------------------------------
monthly_total_sales = np.sum(sales_data, axis=0)

print("\n--- Task 2: Total Sales per Month ---")
for month, total in zip(months, monthly_total_sales):
    print(f"{month}: {total}k")


# --------------------------------------------------
# Task 3: Month with highest total sales
# --------------------------------------------------
max_month_index = np.argmax(monthly_total_sales)

print("\n--- Task 3: Highest Sales Month ---")
print(f"{months[max_month_index]}: {monthly_total_sales[max_month_index]}k")


# --------------------------------------------------
# Task 4: Growth rate for each product
# Growth = ((Last - First) / First) * 100
# --------------------------------------------------
growth_rate = ((sales_data[:, -1] - sales_data[:, 0]) / sales_data[:, 0]) * 100

print("\n--- Task 4: Growth Rate per Product ---")
for product, rate in zip(products, growth_rate):   #======I used AI for function=======
    print(f"{product}: {rate:.2f}%")


# --------------------------------------------------
# Task 5: Products with average monthly sales > 120k
# --------------------------------------------------
average_sales = np.mean(sales_data, axis=1)

print("\n--- Task 5: Products with Average Monthly Sales > 120k ---")
for product, avg in zip(products, average_sales):
    if avg > 120:
        print(f"{product}: {avg:.2f}k")


# --------------------------------------------------
# Task 6: Quarter-wise sales
# Q1 -> Jan, Feb, Mar
# Q2 -> Apr, May, Jun
# --------------------------------------------------
q1_sales = np.sum(sales_data[:, :3], axis=1)
q2_sales = np.sum(sales_data[:, 3:], axis=1)

print("\n--- Task 6: Quarter-wise Sales ---")
for i, product in enumerate(products):
    print(f"{product} - Q1: {q1_sales[i]}k, Q2: {q2_sales[i]}k")


# --------------------------------------------------
# Bonus: Predict July sales
# Method:
# July = average of last 2 months + average monthly growth
# --------------------------------------------------
last_two_month_avg = np.mean(sales_data[:, -2:], axis=1)
monthly_growth_avg = (sales_data[:, -1] - sales_data[:, 0]) / 5

july_prediction = last_two_month_avg + monthly_growth_avg

print("\n--- Bonus: Predicted July Sales ---")
for product, prediction in zip(products, july_prediction):
    print(f"{product}: {prediction:.2f}k")


--- Task 1: Total Sales per Product ---
Product A: 885k
Product B: 630k
Product C: 960k
Product D: 522k

--- Task 2: Total Sales per Month ---
Jan: 440k
Feb: 460k
Mar: 487k
Apr: 503k
May: 537k
Jun: 570k

--- Task 3: Highest Sales Month ---
Jun: 570k

--- Task 4: Growth Rate per Product ---
Product A: 45.83%
Product B: 33.33%
Product C: 20.00%
Product D: 18.75%

--- Task 5: Products with Average Monthly Sales > 120k ---
Product A: 147.50k
Product C: 160.00k

--- Task 6: Quarter-wise Sales ---
Product A - Q1: 405k, Q2: 480k
Product B - Q1: 285k, Q2: 345k
Product C - Q1: 450k, Q2: 510k
Product D - Q1: 247k, Q2: 275k

--- Bonus: Predicted July Sales ---
Product A: 178.50k
Product B: 123.50k
Product C: 181.00k
Product D: 96.50k
